version: "3.9"

services:
  api:
    build: .
    image: bugbounty-aio:latest
    container_name: bugbounty-aio_api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data                      # shared host folder for outputs/jobs
      - /var/run/docker.sock:/var/run/docker.sock  # allow API to control Docker
    restart: unless-stopped

  # Optional idle containers for ProjectDiscovery tools (shown as sleep infinity).
  # The API can also run these images on-demand; keep if you want them visible in Portainer.
  subfinder:
    image: projectdiscovery/subfinder:latest
    container_name: bugbounty-subfinder
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    volumes:
      - ./data:/data
    restart: "no"

  naabu:
    image: projectdiscovery/naabu:latest
    container_name: bugbounty-naabu
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    volumes:
      - ./data:/data
    restart: "no"

  httpx:
    image: projectdiscovery/httpx:latest
    container_name: bugbounty-httpx
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    volumes:
      - ./data:/data
    restart: "no"

  nuclei:
    image: projectdiscovery/nuclei:latest
    container_name: bugbounty-nuclei
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    volumes:
      - ./data:/data
    restart: "no"
