version: "3.8"

services:
  aio:
    container_name: bug-bounty-aio
    build: .
    restart: unless-stopped
    environment:
      - ENV=prod
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - ./settings.json:/app/settings.json:ro
      - aio-data:/app/data

volumes:
  aio-data:
