services:
  backend:
    image: ghcr.io/knothead53/bugbounty-aio-backend:latest
    container_name: bugbounty-backend
    environment:
      - APP_VERSION=${APP_VERSION:-latest}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
