services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: bugbounty-aio-backend:dev
    container_name: bugbounty-backend
    environment:
      - APP_VERSION=0.1.0
    ports:
      - "8080:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
